[tool.black]
line-length = 120
exclude = '''
(
  /(
    | .git
    | venv
    | .venv
  )/
)
'''

[tool.pytest.ini_options]
minversion = "6.2"
timeout = 75
timeout_method = "thread"
testpaths = "tests"
addopts = "-vvv"
