name: jury
channels:
  - anaconda
dependencies:
  - pip
  - python=3.8
  - pip:
    - ipywidgets==7.6.3
    - jury==1.0.0
    - jupyter==1.0.0
    - notebook>=6.4.0
    - sacrebleu==1.5.1
    - bert-score==0.3.9